version: 0.0
os: linux
files:
  - source: /webapp/target/ROOT.war
    destination: /opt/tomcat/webapps
  - source: /webapp/AmazonCloudWatch-config.json
    destination: /opt
hooks:
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu