version: 0.0
os: linux
files:
  - source: /home/circleci/webapp/target/cloud-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps
hooks:
  ApplicationStop:
    - location: /home/circleci/webapp/codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: /home/circleci/webapp/codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: /home/circleci/webapp/codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu