version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  pr_check:
    
    working_directory: ~/webapp # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch 
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgresql
          POSTGRES_DB: users

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - run: mvn dependency:go-offline # gets the project dependencies
      - run: mvn test # run the actual tests


  build:
    
    working_directory: ~/webapp # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch 
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgresql
          POSTGRES_DB: users

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - run: mvn dependency:go-offline # gets the project dependencies     
      - run: mvn test # run the actual tests



workflows:
  version: 2
  pr-check:
    jobs:
    - pr_check
  build-deploy:
    jobs:
    - build:
        filters:
            branches:
                only:
                - master